export const APP_SET_PASSWORD = 'APP/SET_PASSWORD';
export const APP_IMPORT_ACCOUNT = 'APP/IMPORT_ACCOUNT';
export const APP_UPDATE_ACCOUNT = 'APP/UPDATE_ACCOUNT';
export const APP_ACCOUNT_TRANSFER = 'APP/ACCOUNT_TRANSFER';
export const APP_ACCOUNT_STAKING = 'APP/ACCOUNT_STAKING';
export const APP_ACCOUNT_UNSTAKING = 'APP/ACCOUNT_UNSTAKING';
